import Testing
@testable import FlowCore

/// Golden vectors generated by running the Amkette web app's own packet-building
/// code (from its bundles, see docs/protocol.md) under Node, with the same
/// sequence of commands, so the rolling sequence numbers line up.
@Suite struct ProtocolTests {
    func hex(_ s: String) -> [UInt8] { s.split(separator: " ").map { UInt8($0, radix: 16)! } }

    @Test func matchesWebAppPackets() {
        var seq = CommandSequence()
        #expect(MouseProtocol.pollingRate(.hz1000, seq: &seq) == hex(
            "04 02 01 0E 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"))
        #expect(MouseProtocol.dpi(axis: .x, levels: [400, 800, 1200, 1600, 2400, 3200, 6400], currentLevel: 3, sensorType: 3, seq: &seq) == hex(
            "02 03 02 1D 03 7F 03 00 07 00 0B 00 0F 00 17 00 1F 00 3F 00 FF FF FF FF FF FF FF FF FF FF FF"))
        #expect(MouseProtocol.lighting(mode: .breathe, brightness: 4, speed: 3, direction: 0, seq: &seq) == hex(
            "06 04 01 FE FF 02 03 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF"))
        let buttons = MouseProtocol.buttons(OnboardButton.allCases.map(\.factoryCode), seq: &seq)
        #expect(buttons == [
            hex("01 05 02 EC 10 01 00 10 02 00 10 04 00 10 08 00 10 10 00 60 01 00 40 01 00 60 06 00 60 07 00"),
            hex("01 06 12 6F 60 08 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF"),
        ])
        #expect(MouseProtocol.power(sleepMinutes: 10, moveWakeup: true, moveLighting: false, seq: &seq) == hex(
            "07 07 01 08 0A 01 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF"))
        #expect(MouseProtocol.factoryReset(seq: &seq) == hex(
            "0F 08 01 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF"))
    }

    @Test func packetsAre31Bytes() {
        var seq = CommandSequence()
        #expect(MouseProtocol.dpiColors([], seq: &seq).count == 31)
        #expect(MouseProtocol.sensor(angleSnap: false, motionSync: true, ripple: false, seq: &seq).count == 31)
    }

    @Test func sequenceWraps() {
        var seq = CommandSequence()
        var last: UInt8 = 0
        for _ in 0..<300 { last = seq.next() }
        #expect(last == UInt8((1 + 300) % 256))
    }

    @Test func parsesStatusReport() {
        let status = DeviceStatus(report: [1, 2, 1, 85, 0, 3, 0, 1, 3])
        #expect(status?.batteryPercent == 85)
        #expect(status?.pollingRate == .hz1000)
        #expect(status?.sensorName == "S203")
        #expect(DeviceStatus(report: [1, 2]) == nil)
    }

    @Test func consumerCodes() {
        #expect(ButtonCode.consumer(0x18A).bytes == [0x80, 0x8A, 0x01]) // web app "email"
        #expect(ButtonCode.consumer(0xCD).displayName == "Play/Pause")
    }
}
